# Generated by Django 4.2.3 on 2023-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('idfornecedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('produto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('idfuncionarios', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('datanasc', models.DateField(help_text=' formato <em>YYYY-MM-DD</em>')),
                ('funcao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False)),
                ('pagamento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idproduto', models.IntegerField(primary_key=True, serialize=False)),
                ('validade', models.DateTimeField()),
            ],
        ),
    ]
